### ISSUE TITLE
iops option does't work.

### ISSUE THREAD

**Issue by colingpt** [hidden-refuge/bench-sh-2#2]
root@test:~# ./bench.sh -iops

IOPing Benchmark Results
------------------------
./bench.sh: line 162: /root/ioping: No such file or directory
./bench.sh: line 163: /root/ioping: No such file or directory
./bench.sh: line 164: /root/ioping: No such file or directory
./bench.sh: line 165: /root/ioping: No such file or directory
./bench.sh: line 166: /root/ioping: No such file or directory
./bench.sh: line 167: /root/ioping: No such file or directory
./bench.sh: line 168: /root/ioping: No such file or directory
./bench.sh: line 169: /root/ioping: No such file or directory
./bench.sh: line 170: /root/ioping: No such file or directory

Latency (Async):

------------------------

Latency (Direct):

------------------------

Latency (Cache):

------------------------

Seek Rate (Async):

------------------------

Seek Rate (Direct):

------------------------

Seek Rate (Cache):

------------------------

Sequential Speed (Async):

------------------------

Sequential Speed (Direct):

------------------------

Sequential Speed (Cache):

------------------------

root@test:~#

I am using a 512m VM vps with debian 8 x64

**Comment by hidden-refuge** [comment]
Hello,

I've tested it again and I can confirm this issue presists.

I'll be working on a fix.

**Comment by hidden-refuge** [comment]
Can you try again now? I compile ioping 0.9 again this time with all necessary dependencies for 32 and 64 bit.

My test results:
<code>IOPing Benchmark Results
------------------------

Latency (Async):

--- . (simfs /vz/private/104) ioping statistics ---
10 requests completed in 9.00 s, 4.61 k iops, 18.0 MiB/s
min/avg/max/mdev = 178 us / 217 us / 234 us / 14 us
------------------------

Latency (Direct):

--- . (simfs /vz/private/104) ioping statistics ---
10 requests completed in 9.00 s, 4.67 k iops, 18.3 MiB/s
min/avg/max/mdev = 179 us / 213 us / 255 us / 17 us
------------------------

Latency (Cache):

--- . (simfs /vz/private/104) ioping statistics ---
10 requests completed in 9.00 s, 117.6 k iops, 459.6 MiB/s
min/avg/max/mdev = 7 us / 8 us / 10 us / 0 us
------------------------


Seek Rate (Async):

--- . (simfs /vz/private/104) ioping statistics ---
513 requests completed in 3.00 s, 170 iops, 683.7 KiB/s
min/avg/max/mdev = 157 us / 5.85 ms / 16.9 ms / 3.77 ms
------------------------

Seek Rate (Direct):

--- . (simfs /vz/private/104) ioping statistics ---
575 requests completed in 3.01 s, 191 iops, 765.3 KiB/s
min/avg/max/mdev = 155 us / 5.23 ms / 17.4 ms / 3.27 ms
------------------------

Seek Rate (Cache):

--- . (simfs /vz/private/104) ioping statistics ---
1.77 M requests completed in 3.00 s, 637.7 k iops, 2.43 GiB/s
min/avg/max/mdev = 0 us / 1 us / 65 us / 0 us
------------------------


Sequential Speed (Async):

--- . (simfs /vz/private/104) ioping statistics ---
586 requests completed in 3.01 s, 196 iops, 49.2 MiB/s
min/avg/max/mdev = 1.17 ms / 5.08 ms / 14.0 ms / 1.30 ms
------------------------

Sequential Speed (Direct):

--- . (simfs /vz/private/104) ioping statistics ---
603 requests completed in 3.00 s, 202 iops, 50.7 MiB/s
min/avg/max/mdev = 1.17 ms / 4.93 ms / 18.2 ms / 1.05 ms
------------------------

Sequential Speed (Cache):

--- . (simfs /vz/private/104) ioping statistics ---
40.2 k requests completed in 3.00 s, 13.4 k iops, 3.28 GiB/s
min/avg/max/mdev = 66 us / 74 us / 294 us / 8 us
------------------------
</code>

**Comment by hidden-refuge** [comment]
Due to issues with dependencies, kernel versions and other factors I will not fix this. Moreover I will remove the whole iops function.

Fixing it and making something really working on any Linux distribution would break the concenpt of this script. The script is meant to be a easy as possible and mostly use that what really almost any Linux operating system has (grep, cut, sed and et cetera).
