### ISSUE TITLE
Incorrectly Unit for Average I/O

### ISSUE THREAD

**Issue by olragon** [hidden-refuge/bench-sh-2#9]
MB/s instead of GB/s

```
root@pve:~/src# ./bench.sh -io
Disk Speed
----------
I/O (1st run)	: 1.7 GB/s
I/O (2nd run)	: 1.7 GB/s
I/O (3rd run)	: 1.7 GB/s
Average I/O	: 1.7 MB/s

root@pve:~/src# ./bench.sh -io
Disk Speed
----------
I/O (1st run)	: 1.8 GB/s
I/O (2nd run)	: 1.8 GB/s
I/O (3rd run)	: 1.8 GB/s
Average I/O	: 1.8 MB/s

root@pve:~/src# ./bench.sh -io
Disk Speed
----------
I/O (1st run)	: 1.8 GB/s
I/O (2nd run)	: 1.8 GB/s
I/O (3rd run)	: 1.8 GB/s
Average I/O	: 1.8 MB/s
```

**Comment by hidden-refuge** [comment]
@olragon Can you test it please: https://github.com/hidden-refuge/bench-sh-2/blob/dev/bench.sh

The dev branch has a fix that I applied. I have no server that reaches such high speeds to test if it works really. I could only test it by hard coding the values to such high GB/s values.

**Comment by olragon** [comment]
It's work <3
Do you think it will be nicer if Average I/O is also GB/s

```
root@pve:~# ./bench.sh -io
Disk Speed
----------
I/O (1st run)	: 1.6 GB/s
I/O (2nd run)	: 1.7 GB/s
I/O (3rd run)	: 1.6 GB/s
Average I/O	: 1633 MB/s
```

**Comment by hidden-refuge** [comment]
@olragon I added the code to show it also in GB/s. If the average speed is below GB/s value it will show it as .XX where XX is the calculated GB/s value. That's how bc seems to work. Oh yeah and I had to do something I wanted to avoid but bash without anything else simply cannot operate with floats. So now bc is a requirement for the I/O test. The I/O test will exit when bc is not installed and abort the script with an error message.

Test it again please. I tested it with hardcoded values and it worked. I also tested on a server with much lower speeds and it also works.

**Comment by olragon** [comment]
It's work better now (y)

```
root@pve:~# ./bench.sh -io
Disk Speed
----------
I/O (1st run)	: 1.7 GB/s
I/O (2nd run)	: 1.7 GB/s
I/O (3rd run)	: 1.7 GB/s
Average I/O	: 1700 MB/s or 1.70 GB/s
```
